dist: bionic
language: python

sudo: false

matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35-django22
    - python: 3.6
      env: TOX_ENV=py36-django22
    - python: 3.7
      env: TOX_ENV=py37-django22
    - python: 3.8
      env: TOX_ENV=py38-django22
    - python: 3.6
      env: TOX_ENV=py36-django30
    - python: 3.7
      env: TOX_ENV=py37-django30
    - python: 3.8
      env: TOX_ENV=py38-django30
    - python: 3.6
      env: TOX_ENV=py36-djangomaster
    - python: 3.7
      env: TOX_ENV=py37-djangomaster
    - python: 3.8
      env: TOX_ENV=py38-djangomaster
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py36-djangomaster
    - env: TOX_ENV=py37-djangomaster
    - env: TOX_ENV=py38-djangomaster

addons:
  apt:
    packages:
    - xmlsec1

install:
    - pip install --upgrade pip setuptools tox virtualenv rstcheck

script:
    - tox -e $TOX_ENV
    - rstcheck README.rst

after_success:
    - pip install codecov
    - codecov -e TOX_ENV,TRAVIS_PYTHON_VERSION

notifications:
    email: false
